# Generated by Django 4.2.16 on 2026-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_reports_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ceo_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gst_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
