# Generated by Django 4.2.16 on 2026-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_ceo_name_customuser_company_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialGSTData",
            fields=[
                (
                    "gstin",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("status", models.CharField(default="Active", max_length=50)),
            ],
            options={
                "db_table": "official_gst_data",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
