# Generated by Django 4.2.16 on 2026-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referralusage",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="referralusage",
            constraint=models.UniqueConstraint(
                fields=("code", "used_by"), name="unique_referral_usage"
            ),
        ),
    ]
