# Generated by Django 4.2.16 on 2026-04-18 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("event", "Event"),
                            ("post", "Post"),
                            ("company", "Company"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.CharField(max_length=36)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="reports_target__f1c53d_idx",
                    ),
                    models.Index(
                        fields=["reporter"], name="reports_reporte_5cbb43_idx"
                    ),
                ],
            },
        ),
    ]
