# Generated by Django 4.2.16 on 2026-04-18 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyclaim",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="company",
            name="reports_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="company",
            name="trust_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="companyclaim",
            constraint=models.UniqueConstraint(
                fields=("company", "user"), name="unique_company_claim"
            ),
        ),
    ]
