# Generated by Django 4.2.16 on 2026-04-18 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_online", models.BooleanField(default=False)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("trust_score", models.IntegerField(default=0)),
                ("reports_count", models.PositiveIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_registrations",
                "indexes": [
                    models.Index(
                        fields=["event"], name="event_regis_event_i_343f8e_idx"
                    ),
                    models.Index(
                        fields=["user"], name="event_regis_user_id_c9d271_idx"
                    ),
                ],
                "unique_together": {("event", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["organizer"], name="events_organiz_1c7a2e_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_flagged"], name="events_is_flag_43f9ec_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="events_date_e70fc0_idx"),
        ),
    ]
