# Generated by Django 4.2.16 on 2026-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_registration_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("Networking", "Networking"),
                    ("Conference", "Conference"),
                    ("Workshop", "Workshop"),
                    ("Investor", "Investor"),
                    ("Hackathon", "Hackathon"),
                    ("General", "General"),
                ],
                default="Networking",
                max_length=50,
            ),
        ),
    ]
