# Generated by Django 4.2.16 on 2026-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_application_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(blank=True, default="Full-time", max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="work_mode",
            field=models.CharField(blank=True, default="On-site", max_length=50),
        ),
    ]
