# Generated by Django 4.2.16 on 2026-04-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_like_unique_together_post_reports_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_repost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="original_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="feed.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="poll_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("poll", "Poll"),
                    ("event", "Event"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="media_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
