# Generated by Django 4.2.16 on 2026-04-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_post_is_repost_post_original_post_post_poll_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media_url",
        ),
        migrations.AddField(
            model_name="post",
            name="media_file",
            field=models.FileField(blank=True, null=True, upload_to="feed_media/"),
        ),
    ]
