/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppVerifyRouteImport } from './routes/_app.verify'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReferralsRouteImport } from './routes/_app.referrals'
import { Route as AppPromotionsRouteImport } from './routes/_app.promotions'
import { Route as AppNetworkRouteImport } from './routes/_app.network'
import { Route as AppFundingRouteImport } from './routes/_app.funding'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppB2bRouteImport } from './routes/_app.b2b'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app.companies.index'
import { Route as AppProfileEditRouteImport } from './routes/_app.profile.edit'
import { Route as AppProfileUserIdRouteImport } from './routes/_app.profile.$userId'
import { Route as AppJobsJobIdRouteImport } from './routes/_app.jobs.$jobId'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/_app.events.$eventId'
import { Route as AppCompaniesClaimRouteImport } from './routes/_app.companies.claim'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app.companies.$companyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppFundingRoute = AppFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppB2bRoute = AppB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesClaimRoute = AppCompaniesClaimRouteImport.update({
  id: '/companies/claim',
  path: '/companies/claim',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/b2b': typeof AppB2bRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRoute
  '/funding': typeof AppFundingRoute
  '/network': typeof AppNetworkRoute
  '/promotions': typeof AppPromotionsRoute
  '/referrals': typeof AppReferralsRoute
  '/settings': typeof AppSettingsRoute
  '/verify': typeof AppVerifyRoute
  '/wallet': typeof AppWalletRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/companies/claim': typeof AppCompaniesClaimRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/b2b': typeof AppB2bRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRoute
  '/funding': typeof AppFundingRoute
  '/network': typeof AppNetworkRoute
  '/promotions': typeof AppPromotionsRoute
  '/referrals': typeof AppReferralsRoute
  '/settings': typeof AppSettingsRoute
  '/verify': typeof AppVerifyRoute
  '/wallet': typeof AppWalletRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/companies/claim': typeof AppCompaniesClaimRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/jobs': typeof AppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/b2b': typeof AppB2bRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/funding': typeof AppFundingRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/verify': typeof AppVerifyRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/companies/claim': typeof AppCompaniesClaimRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/b2b'
    | '/dashboard'
    | '/feed'
    | '/funding'
    | '/network'
    | '/promotions'
    | '/referrals'
    | '/settings'
    | '/verify'
    | '/wallet'
    | '/companies/$companyId'
    | '/companies/claim'
    | '/events/$eventId'
    | '/events/new'
    | '/jobs/$jobId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/companies/'
    | '/events/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/b2b'
    | '/dashboard'
    | '/feed'
    | '/funding'
    | '/network'
    | '/promotions'
    | '/referrals'
    | '/settings'
    | '/verify'
    | '/wallet'
    | '/companies/$companyId'
    | '/companies/claim'
    | '/events/$eventId'
    | '/events/new'
    | '/jobs/$jobId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/companies'
    | '/events'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/b2b'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/funding'
    | '/_app/network'
    | '/_app/promotions'
    | '/_app/referrals'
    | '/_app/settings'
    | '/_app/verify'
    | '/_app/wallet'
    | '/_app/companies/$companyId'
    | '/_app/companies/claim'
    | '/_app/events/$eventId'
    | '/_app/events/new'
    | '/_app/jobs/$jobId'
    | '/_app/profile/$userId'
    | '/_app/profile/edit'
    | '/_app/companies/'
    | '/_app/events/'
    | '/_app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify': {
      id: '/_app/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funding': {
      id: '/_app/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof AppFundingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b2b': {
      id: '/_app/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof AppB2bRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/claim': {
      id: '/_app/companies/claim'
      path: '/companies/claim'
      fullPath: '/companies/claim'
      preLoaderRoute: typeof AppCompaniesClaimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppB2bRoute: typeof AppB2bRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFundingRoute: typeof AppFundingRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppWalletRoute: typeof AppWalletRoute
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppCompaniesClaimRoute: typeof AppCompaniesClaimRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppB2bRoute: AppB2bRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRoute,
  AppFundingRoute: AppFundingRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppWalletRoute: AppWalletRoute,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppCompaniesClaimRoute: AppCompaniesClaimRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
